language: java

jdk:
  - oraclejdk8
sudo: false
env:
  - NODE_VERSION=4.3.2
before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm
  - npm install -g gulp
  - npm install -g bower
  - chmod +x gradlew
install: npm install && bower install
before_script: 
  - gulp build
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
script:
  - gulp test
  - ./gradlew build --info
  - ./gradlew test --info

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
