language: java
node_js:
  - "4.3.2"
jdk:
  - oraclejdk8
sudo: true
before_install:
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  - gradle npm_install -g npm
  - gradle npm_update
  - gradle npm_install -g gulp
install:
  - gradle npm_install
  - gradle npm_install karma-firefox-launcher --save-dev
  - gradle npm_install
before_script:
  - gradle build
  - gradle gulp_build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
