language: java
node_js:
  - "4.3.2"
jdk:
  - oraclejdk8
sudo: true
before_install:
  - wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
  - sudo apt-get install --yes nodejs
install:
  - npm install -g npm
  - npm update
  - npm install -g gulp
  - npm install
before_script:
  - gulp build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
