language: node_js
node_js:
  - "4.3.2"
jdk:
  - oraclejdk8
sudo: true
before_install:
  - npm install -g npm
  - npm install -g gulp
  - npm install bower
  - chmod +x gradlew
install: npm install
before_script: gulp build
script:
  - gulp test
  - sudo ./gradlew build
  - sudo ./gradlew test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
