language: java

jdk:
  - oraclejdk8
sudo: required
env:
  - NODE_VERSION=4.3.2
before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm
  - npm install -g gulp
  - npm install -g bower
  - chmod +x gradlew
install: npm install && bower install
before_script: 
  - gulp build
  - sudo /etc/init.d/mysql stop || true
  - sudo /etc/init.d/memcached stop || true
  - sudo /etc/init.d/bootlogd stop || true
  - sudo /etc/init.d/mongodb stop || true
  - sudo /etc/init.d/neo4j stop || true
  - sudo /etc/init.d/cassandra stop || true
  - sudo /etc/init.d/riak stop || true
  - sudo /etc/init.d/rsync stop || true
  - sudo /etc/init.d/x11-common stop || true
script:
  - gulp test
  - ./gradlew build
  - ./gradlew test

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  email: true
