version: '2'
services:
    volunteercrowd-app:
        image: volunteercrowd
        external_links:
            - volunteercrowd-postgresql:postgresql
            - volunteercrowd-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/Volunteercrowd
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    volunteercrowd-postgresql:
        extends:
            file: postgresql.yml
            service: volunteercrowd-postgresql
    volunteercrowd-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: volunteercrowd-elasticsearch
