volunteercrowd-elasticsearch:
  container_name: volunteercrowd-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/Volunteercrowd/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
volunteercrowd-postgresql:
  container_name: volunteercrowd-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/Volunteercrowd/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=Volunteercrowd
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
